stages:
  mtcars:
    cmd: Rscript R/mtcars.R
    deps:
      - R/mtcars.R
    outs:
      - brick/mtcars.parquet
  iris_sqlite:
    cmd: Rscript R/build_iris_sqlite.R
    outs:
      - brick/iris.sqlite
  nested_tbls:
    cmd: Rscript R/build_nested_namespace.R
    outs:
      - brick/rtbls/